name: Auto_2_Sim

on:
  workflow_dispatch:

jobs:
  run-simulation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run Engine
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          ROLLING_GAMES_WINDOW: 15
        run: python main.py
